# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: registry.stage1.ng.bluemix.net/ddcao_5sep_namespace/ddcao-5sep-529
  tag: v1.0.0
  pullPolicy: Always
livenessProbe:
  initialDelaySeconds: 3000
  periodSeconds: 1000
service:
  name: Node
  type: NodePort
  servicePort: 3000
services:
