version : 0.0.3

container-name-run : "dcao project 7sep-express-run"
container-name-tools : "dcao project 7sep-express-tools"

host-path-run : .
host-path-tools : .

container-path-run : "/app"
container-path-tools : "/app"

container-port-map : "3000:3000"
container-port-map-debug : "5858:5858"

dockerfile-run : "Dockerfile"
dockerfile-tools : "Dockerfile-tools"

image-name-run : "dcao project 7sep-express-run"
image-name-tools : "dcao project 7sep-express-tools"

build-cmd-run : "npm install"
test-cmd : "npm run test"
build-cmd-debug : "npm install"

run-cmd : ""
debug-cmd : "npm run debug"
stop-cmd : "npm stop"

chart-path: "chart/dcao project 7sep"
