stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  jobs:
  - name: Build
    type: builder
    artifact_dir : ''
  - name: Container Build
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      
      IMAGE_NAME=ddcao-5sep-529
      REGISTRY_URL=registry.stage1.ng.bluemix.net/ddcao_5sep_namespace
      FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:v1.0.0

      echo "FULL_REPOSITORY_NAME: ${FULL_REPOSITORY_NAME}"
      
      if [ -f Dockerfile ]; then 
          # build image
          echo "BUILDING Dockerfile"

          docker build -t "${FULL_REPOSITORY_NAME}" .

          echo "BUILDING Dockerfile finished"

          docker push "${FULL_REPOSITORY_NAME}"
      else 
          echo "Dockerfile not found at the repository root"
          exit 1
      fi
  - name: Post Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      if  [[ -f post_build.sh ]]; then
        chmod +x post_build.sh;
        echo "executing the post_build script";
        sh post_build.sh;
      else
        echo "the post_build script does not exist";
      fi
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Container Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${CF_REGION_ID}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    script: |
      #!/bin/bash
      #set -x

      helm init
      helm install ./chart/ddcaocoolapp
      echo "finished installing chart"